matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '10'
  - os: linux
    language: node_js
    node_js: '10'
    services: docker
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3 && yarn install && yarn test
      docker run --rm \
       --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
        --env ELECTRON_CACHE="/root/.cache/electron" \
        --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "./script/install-redis.sh && npm rebuild node-sass && yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
    else
      brew install redis && yarn install && yarn test && yarn release
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
env:
  matrix:
    secure: BCRFNtXdMaGhVvfgZhTZiYwpE5u8CNAWp89Ly0sW8sVVzYO4bVJXF5tRqOsysI1ti+LHe2QWYsGeNRs6q8zPWHg0JEA0PwZE5AkZu/rdYDzapZ1WILkfzAKnqUMnEHE8NFdp9X5L29r7Gy5povlPIwbCakXHWsiJc322WrtoNfCAYn9i6RmsLRCux+UPULS+SHaGbxLuunh0uDXkur8jIAj1Q+qVy7jnuNGtJq2AERFobSSoRCbYb99nnHMY7RlQ1bCn9cLy24/vBc0uXSZyy6qn2Aka0HOxZi18Ok7fhFuXX3w9OlHbrlrK9m9/OzSASfPZQmiO0gDdfCSLHdW4Xvl+0SrJ92WD2aJnxdKwLPQXlyP1fvUPvwxrJqaLAFqVcBCxuptUCsrpPd9X6YvIlQsTfEZdOdVLJTRTKAffpAq+X84diveue697kNsKkFvl2vZDynpz4+r9dDsdEfOrJb7VfstASkPq7qyJ4Z1I2ZQRJG6bTVAX5qFZOkmj80zNRYWdJOHbzjfB2krBHH/wh/rny1eI/0hDh+mzSqxyLh+WtHFnQsYp14RPKOZhcKA2CizLYgHfC+kzotzTzD/lbDHtrXqOcKvi8kmpUC2c7tCql1mLhU2g04301glYSA+af7/i4YeledBAJ8VNfbuYaWuHY/jg06LwdA7SZljRB+U=
notifications:
  email:
    on_success: never
    on_failure: change
